name: martin_pulgar_construction
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  beamer: ^1.5.6
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  equatable: ^2.0.5
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.19.0
  image_picker: ^0.8.4+4
  intl: ^0.18.1
  permission_handler: ^10.4.3


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
